[project]
name = "crudapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[stander]>=0.128.2",
    "uvicorn>=0.40.0",
]
